# Generated by Django 4.1.1 on 2022-10-04 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('articulo', models.TextField(verbose_name='Articulo')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('fotoPortada', models.ImageField(blank=True, null=True, upload_to='fotos/articulos/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Foto de Portada')),
            ],
        ),
    ]
